-- Deprecated one-off migration.
-- Use supabase/admin-approval-rls.sql instead: it creates students, adds instructor approval,
-- and replaces the old open MVP RLS policies with stricter production-style policies.
